using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using AirlineLibrary;

namespace Airline
{
    /// <summary>
    /// Interaction logic for ItineraryWindow.xaml
    /// </summary>
    public partial class ItineraryWindow : Window
    {
        private Itinerary<object> itinerary;

        public Itinerary<object> Itinerary
        {
            get { return itinerary; }
            set { itinerary = value; }
        }

        public ItineraryWindow()
        {
            InitializeComponent();
            ItineraryWindow i = new ItineraryWindow();
            i.Show();
        }
        
        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            Origin o = new Origin();
            Destination d = new Destination();
            AirPlane a = new AirPlane();
            Passenger p = new Passenger();
            Seat s = new Seat();
            Itinerary<object> DataViewModel = new Itinerary<object>(o, d, a, p, s);
        }
    }
}
